/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:15db8e18-6685-4515-89cf-2e691a75de6e",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_gxRAByq3d",
    "aws_user_pools_web_client_id": "45bnl9dtma01f1e5kfinl5u3lr",
    "oauth": {},
    "aws_cognito_username_attributes": [],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_cloud_logic_custom": [
        {
            "name": "AdminQueries",
            "endpoint": "https://vt25y4u1n1.execute-api.us-east-1.amazonaws.com/dev",
            "region": "us-east-1"
        }
    ],
    "aws_user_files_s3_bucket": "cloudkelvinv26ae35849a4104091a533f1be1213b752e2bbe-dev",
    "aws_user_files_s3_bucket_region": "us-east-1"
};


export default awsmobile;
